### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by kaythomas0**
Some people want to run this application in a docker container, so adding a Dockerfile to the repo could be helpful to them.

### CODE REVIEW

**Comment by ikreymer** [comment]
Generally I'm in favor of adding Dockerfile to applications, however, in this case, this may be more complicated than what is needed. I suppose this could be useful for development, if you want to run with `yarn run start-dev`.

However, the whole site is just a static site, so it should be runnable from just any web server, eg. `http-server -p 9990` or `python -m http.server 9990` or placing it on an Nginx and Apache server, there's no need to install to just run the production version.

Perhaps we need to update the docs to make this more clear...

**Comment by ikreymer** [comment]
@kaythomas0 Does this update help cover what you're looking for? https://github.com/webrecorder/replayweb.page#running-replaywebpage

Or are you interested in using Docker for development instead of installing node locally?

**Comment by kaythomas0** [comment]
@ikreymer Hey thanks for the response! I understand and I can close this. I mainly did this because I knew some colleagues who wanted to run this in a Docker container and they came to me for help, and I figured I could just make a PR with the Dockerfile to the repo, but your reasoning makes sense to me. I can just share with them the Dockerfile directly if they still want to use Docker to run it.

**Comment by ikreymer** [comment]
If you don't mind, curious about the use case you and your colleagues have for replayweb.page and how you were thinking of using it. Are you using in context of game development in some way? Perhaps there's other ways we can help!
Feel free to reach out via email as well info [at] webrecorder.net

**Pull request closed without merging**
